const allProducts = [
  {
    name: "pechuga-pavo",
    initialPrice: "62.50",
    gramos: "250 g ($0.25/gr)",
    description: "San Rafael pechuga de pavo",
    finalPrice: 62.5,
    finalGramos: 0,
  },
  {
    name: "pan",
    initialPrice: "38.90",
    gramos: "680 g ($0.6/gr)",
    description: "Bimbo Pan Blanco Grande",
    finalPrice: 38.9,
    finalGramos: 0,
  },
  {
    name: "mayonesa",
    initialPrice: "48.50",
    gramos: "507 g ($0.1/gr)",
    description: "Mc Cormick Mayonesa",
    finalPrice: 48.5,
    finalGramos: 0,
  },

  {
    name: "colgate",
    initialPrice: "35.50",
    gramos: "125 ml ($0.28/ml)",
    description: "Colgate Pasta Dental Triple Familiar 2 U",
    finalPrice: 35.5,
    finalGramos: 0,
  },
  {
    name: "huevos",
    initialPrice: "37.50",
    gramos: "18 Und ($2.08/u)",
    description: "Huevos San Juan",
    finalPrice: 37.5,
    finalGramos: 0,
  },
  {
    name: "fabuloso",
    initialPrice: "26.50",
    gramos: "500 ml ($0.06/ml)",
    description: "Fabulosa , limpia todo.",
    finalPrice: 26.5,
    finalGramos: 0,
  },
  {
    discount: 32,
    name: "limon",
    initialPrice: "26.82",
    precioAntes: "39.90",
    description: "Limon con semilla.",
    finalPrice: 26.82,
    finalGramos: 0,
  },
  {
    discount: 32,
    name: "tomate-rojo",
    initialPrice: "21.79",
    precioAntes: "32.90",
    description: "Tomate Fresco de granja",
    finalPrice: 21.79,
    finalGramos: 0,
  },
  {
    discount: 18,
    name: "aguacate",
    initialPrice: "56.80",
    precioAntes: "69.90",
    description: "Aguacate Hass Fresco",
    finalPrice: 56.8,
    finalGramos: 0,
  },
  {
    discount: 13,
    name: "nopal",
    initialPrice: "25.80",
    precioAntes: "29.90",
    description: "Nopal limpio",
    finalPrice: 25.8,
    finalGramos: 0,
  },
  {
    discount: 8,
    name: "tomate-verde",
    initialPrice: "22.89",
    precioAntes: "24.90",
    description: "Tomate verde fresco de granja",
    finalPrice: 22.89,
    finalGramos: 0,
  },
];

export default allProducts;
