const ofertas = [
  {
    discount: 32,
    name: "limon",
    initialPrice: "26.82",
    precioAntes: "39.90",
    description: "Limon con semilla.",
    finalPrice: 26.82,
    finalGramos: 0,
  },
  {
    discount: 32,
    name: "tomate-rojo",
    initialPrice: "21.79",
    precioAntes: "32.90",
    description: "Tomate Fresco de granja",
    finalPrice: 21.7,
    finalGramos: 0,
  },
  {
    discount: 18,
    name: "aguacate",
    initialPrice: "56.80",
    precioAntes: "69.90",
    description: "Aguacate Hass Fresco",
    finalPrice: 56.8,
    finalGramos: 0,
  },
  {
    discount: 13,
    name: "nopal",
    initialPrice: "25.80",
    precioAntes: "29.90",
    description: "Nopal limpio",
    finalPrice: 25.8,
    finalGramos: 0,
  },
  {
    discount: 8,
    name: "tomate-verde",
    initialPrice: "22.90",
    precioAntes: "24.90",
    description: "Tomate verde fresco de granja",
    finalPrice: 22.9,
    finalGramos: 0,
  },
];
export default ofertas;
